FROM node:22.12.0 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN rm -rf vitest 
RUN rm -rf vitest.config.ts

RUN npm run build

FROM nginx:1.25.0-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD [ "nginx", "-g", "daemon off;" ]